# Generated by Django 3.2.5 on 2021-11-13 22:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20211113_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('P', 'Prefer to not say')], default=None, max_length=2, null=True),
        ),
    ]
