# Generated by Django 3.2.5 on 2021-11-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20211116_1515'),
        ('learn', '0009_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='interest',
        ),
        migrations.AddField(
            model_name='student',
            name='interest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
